/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

export interface RankedUniversity {
  rank: number;
  name: string;
  country: string;
  city: string;
  score: number;
  website: string;
  acceptanceRate: string;
  category: string;
}

export const TOP_100_RANKINGS: RankedUniversity[] = [
  { rank: 1, name: "Massachusetts Institute of Technology (MIT)", country: "USA", city: "Cambridge", score: 100.0, website: "https://www.mit.edu", acceptanceRate: "4.8%", category: "stem_tech" },
  { rank: 2, name: "University of Cambridge", country: "UK", city: "Cambridge", score: 99.2, website: "https://www.cam.ac.uk", acceptanceRate: "18.0%", category: "ivy_elite" },
  { rank: 3, name: "University of Oxford", country: "UK", city: "Oxford", score: 98.9, website: "https://www.ox.ac.uk", acceptanceRate: "15.0%", category: "ivy_elite" },
  { rank: 4, name: "Harvard University", country: "USA", city: "Cambridge", score: 98.3, website: "https://www.harvard.edu", acceptanceRate: "3.4%", category: "ivy_elite" },
  { rank: 5, name: "Stanford University", country: "USA", city: "Stanford", score: 98.1, website: "https://www.stanford.edu", acceptanceRate: "3.9%", category: "ivy_elite" },
  { rank: 6, name: "Imperial College London", country: "UK", city: "London", score: 97.8, website: "https://www.imperial.ac.uk", acceptanceRate: "14.3%", category: "stem_tech" },
  { rank: 7, name: "ETH Zurich (Swiss Federal Institute of Technology)", country: "Switzerland", city: "Zurich", score: 95.4, website: "https://ethz.ch", acceptanceRate: "27.0%", category: "europe_low_tuition" },
  { rank: 8, name: "National University of Singapore (NUS)", country: "Singapore", city: "Singapore", score: 92.7, website: "https://www.nus.edu.sg", acceptanceRate: "15.0%", category: "asian_top" },
  { rank: 9, name: "University College London (UCL)", country: "UK", city: "London", score: 92.4, website: "https://www.ucl.ac.uk", acceptanceRate: "12.0%", category: "ivy_elite" },
  { rank: 10, name: "University of California, Berkeley (UCB)", country: "USA", city: "Berkeley", score: 91.9, website: "https://www.berkeley.edu", acceptanceRate: "11.4%", category: "stem_tech" },
  { rank: 11, name: "University of Chicago", country: "USA", city: "Chicago", score: 91.5, website: "https://www.uchicago.edu", acceptanceRate: "5.4%", category: "ivy_elite" },
  { rank: 12, name: "University of Pennsylvania", country: "USA", city: "Philadelphia", score: 91.1, website: "https://www.upenn.edu", acceptanceRate: "5.9%", category: "business_finance" },
  { rank: 13, name: "Cornell University", country: "USA", city: "Ithaca", score: 90.7, website: "https://www.cornell.edu", acceptanceRate: "7.3%", category: "ivy_elite" },
  { rank: 14, name: "The University of Melbourne", country: "Australia", city: "Melbourne", score: 90.1, website: "https://www.unimelb.edu.au", acceptanceRate: "30.0%", category: "ivy_elite" },
  { rank: 15, name: "California Institute of Technology (Caltech)", country: "USA", city: "Pasadena", score: 89.9, website: "https://www.caltech.edu", acceptanceRate: "3.9%", category: "stem_tech" },
  { rank: 16, name: "Yale University", country: "USA", city: "New Haven", score: 89.6, website: "https://www.yale.edu", acceptanceRate: "4.5%", category: "ivy_elite" },
  { rank: 17, name: "Peking University", country: "China", city: "Beijing", score: 89.1, website: "https://english.pku.edu.cn", acceptanceRate: "1.0%", category: "asian_top" },
  { rank: 18, name: "Princeton University", country: "USA", city: "Princeton", score: 88.8, website: "https://www.princeton.edu", acceptanceRate: "4.0%", category: "ivy_elite" },
  { rank: 19, name: "Tsinghua University", country: "China", city: "Beijing", score: 88.4, website: "https://www.tsinghua.edu.cn", acceptanceRate: "1.5%", category: "asian_top" },
  { rank: 20, name: "Nanyang Technological University (NTU)", country: "Singapore", city: "Singapore", score: 88.0, website: "https://www.ntu.edu.sg", acceptanceRate: "15.0%", category: "asian_top" },
  { rank: 21, name: "The University of Sydney", country: "Australia", city: "Sydney", score: 87.5, website: "https://www.sydney.edu.au", acceptanceRate: "35.0%", category: "ivy_elite" },
  { rank: 22, name: "The University of New South Wales (UNSW)", country: "Australia", city: "Sydney", score: 87.2, website: "https://www.unsw.edu.au", acceptanceRate: "30.0%", category: "ivy_elite" },
  { rank: 23, name: "University of Toronto", country: "Canada", city: "Toronto", score: 86.8, website: "https://www.utoronto.ca", acceptanceRate: "43.0%", category: "ivy_elite" },
  { rank: 24, name: "The University of Edinburgh", country: "UK", city: "Edinburgh", score: 86.4, website: "https://www.ed.ac.uk", acceptanceRate: "10.0%", category: "ivy_elite" },
  { rank: 25, name: "Columbia University", country: "USA", city: "New York", score: 86.1, website: "https://www.columbia.edu", acceptanceRate: "3.9%", category: "ivy_elite" },
  { rank: 26, name: "Université PSL (Paris Sciences & Lettres)", country: "France", city: "Paris", score: 85.5, website: "https://www.psl.eu", acceptanceRate: "12.0%", category: "europe_low_tuition" },
  { rank: 27, name: "University of California, San Diego (UCSD)", country: "USA", city: "San Diego", score: 84.9, website: "https://ucsd.edu", acceptanceRate: "23.0%", category: "stem_tech" },
  { rank: 28, name: "Technical University of Munich (TUM)", country: "Germany", city: "Munich", score: 84.5, website: "https://www.tum.de", acceptanceRate: "8.0%", category: "europe_low_tuition" },
  { rank: 29, name: "University of California, Los Angeles (UCLA)", country: "USA", city: "Los Angeles", score: 84.1, website: "https://www.ucla.edu", acceptanceRate: "9.0%", category: "ivy_elite" },
  { rank: 30, name: "McGill University", country: "Canada", city: "Montreal", score: 83.7, website: "https://www.mcgill.ca", acceptanceRate: "46.0%", category: "ivy_elite" },
  { rank: 31, name: "Bocconi University", country: "Italy", city: "Milan", score: 83.2, website: "https://www.unibocconi.eu", acceptanceRate: "15.0%", category: "business_finance" },
  { rank: 32, name: "University of Manchester", country: "UK", city: "Manchester", score: 82.8, website: "https://www.manchester.ac.uk", acceptanceRate: "26.0%", category: "ivy_elite" },
  { rank: 33, name: "The University of Queensland", country: "Australia", city: "Brisbane", score: 82.4, website: "https://www.uq.edu.au", acceptanceRate: "40.0%", category: "ivy_elite" },
  { rank: 34, name: "King's College London", country: "UK", city: "London", score: 82.1, website: "https://www.kcl.ac.uk", acceptanceRate: "13.0%", category: "ivy_elite" },
  { rank: 35, name: "Seoul National University (SNU)", country: "South Korea", city: "Seoul", score: 81.7, website: "https://en.snu.ac.kr", acceptanceRate: "14.0%", category: "asian_top" },
  { rank: 36, name: "The Hong Kong University of Science and Technology (HKUST)", country: "Hong Kong", city: "Hong Kong", score: 81.2, website: "https://hkust.edu.hk", acceptanceRate: "25.0%", category: "asian_top" },
  { rank: 37, name: "Monash University", country: "Australia", city: "Melbourne", score: 80.9, website: "https://www.monash.edu", acceptanceRate: "40.0%", category: "ivy_elite" },
  { rank: 38, name: "Paris-Saclay University", country: "France", city: "Paris", score: 80.5, website: "https://www.universite-paris-saclay.fr", acceptanceRate: "11.0%", category: "europe_low_tuition" },
  { rank: 39, name: "New York University (NYU)", country: "USA", city: "New York", score: 80.1, website: "https://www.nyu.edu", acceptanceRate: "8.0%", category: "business_finance" },
  { rank: 40, name: "The University of Tokyo", country: "Japan", city: "Tokyo", score: 79.8, website: "https://www.u-tokyo.ac.jp", acceptanceRate: "9.5%", category: "asian_top" },
  { rank: 41, name: "Kyoto University", country: "Japan", city: "Kyoto", score: 79.2, website: "https://www.kyoto-u.ac.jp", acceptanceRate: "10.0%", category: "asian_top" },
  { rank: 42, name: "Northwestern University", country: "USA", city: "Evanston", score: 78.9, website: "https://www.northwestern.edu", acceptanceRate: "7.0%", category: "ivy_elite" },
  { rank: 43, name: "London School of Economics (LSE)", country: "UK", city: "London", score: 78.4, website: "https://www.lse.ac.uk", acceptanceRate: "9.0%", category: "business_finance" },
  { rank: 44, name: "Fudan University", country: "China", city: "Shanghai", score: 78.1, website: "https://www.fudan.edu.cn", acceptanceRate: "2.0%", category: "asian_top" },
  { rank: 45, name: "Zhejiang University", country: "China", city: "Hangzhou", score: 77.7, website: "https://www.zju.edu.cn", acceptanceRate: "3.0%", category: "asian_top" },
  { rank: 46, name: "KAIST (Korea Advanced Institute of Science & Tech)", country: "South Korea", city: "Daejeon", score: 77.4, website: "https://www.kaist.ac.kr", acceptanceRate: "15.0%", category: "stem_tech" },
  { rank: 47, name: "University of British Columbia", country: "Canada", city: "Vancouver", score: 77.1, website: "https://www.ubc.ca", acceptanceRate: "52.0%", category: "ivy_elite" },
  { rank: 48, name: "EPFL (Ecole Polytechnique Fédérale de Lausanne)", country: "Switzerland", city: "Lausanne", score: 76.5, website: "https://www.epfl.ch", acceptanceRate: "20.0%", category: "stem_tech" },
  { rank: 49, name: "Sorbonne University", country: "France", city: "Paris", score: 75.9, website: "https://www.sorbonne-universite.fr", acceptanceRate: "15.0%", category: "europe_low_tuition" },
  { rank: 50, name: "Ludwig Maximilian University of Munich (LMU)", country: "Germany", city: "Munich", score: 75.4, website: "https://www.lmu.de", acceptanceRate: "15.0%", category: "europe_low_tuition" },
  { rank: 51, name: "Yonsei University", country: "South Korea", city: "Seoul", score: 75.0, website: "https://uic.yonsei.ac.kr", acceptanceRate: "18.0%", category: "asian_top" },
  { rank: 52, name: "Osaka University", country: "Japan", city: "Osaka", score: 74.3, website: "https://www.osaka-u.ac.jp", acceptanceRate: "12.0%", category: "asian_top" },
  { rank: 53, name: "Tohoku University", country: "Japan", city: "Sendai", score: 73.8, website: "https://www.tohoku.ac.jp", acceptanceRate: "14.0%", category: "asian_top" },
  { rank: 54, name: "Heidelberg University", country: "Germany", city: "Heidelberg", score: 73.4, website: "https://www.uni-heidelberg.de", acceptanceRate: "15.0%", category: "europe_low_tuition" },
  { rank: 55, name: "Delft University of Technology", country: "Netherlands", city: "Delft", score: 72.9, website: "https://www.tudelft.nl", acceptanceRate: "30.0%", category: "stem_tech" },
  { rank: 56, name: "University of Bristol", country: "UK", city: "Bristol", score: 72.4, website: "https://www.bristol.ac.uk", acceptanceRate: "20.0%", category: "ivy_elite" },
  { rank: 57, name: "University of Warwick", country: "UK", city: "Coventry", score: 71.9, website: "https://warwick.ac.uk", acceptanceRate: "14.5%", category: "ivy_elite" },
  { rank: 58, name: "Korea University", country: "South Korea", city: "Seoul", score: 71.5, website: "https://www.korea.edu", acceptanceRate: "16.0%", category: "asian_top" },
  { rank: 59, name: "Shanghai Jiao Tong University", country: "China", city: "Shanghai", score: 71.1, website: "https://en.sjtu.edu.cn", acceptanceRate: "2.5%", category: "asian_top" },
  { rank: 60, name: "The University of Adelaide", country: "Australia", city: "Adelaide", score: 70.8, website: "https://www.adelaide.edu.au", acceptanceRate: "38.0%", category: "ivy_elite" },
  { rank: 61, name: "University of Glasgow", country: "UK", city: "Glasgow", score: 70.4, website: "https://www.gla.ac.uk", acceptanceRate: "18.0%", category: "ivy_elite" },
  { rank: 62, name: "KU Leuven", country: "Belgium", city: "Leuven", score: 69.9, website: "https://www.kuleuven.be", acceptanceRate: "20.0%", category: "europe_low_tuition" },
  { rank: 63, name: "University of Amsterdam", country: "Netherlands", city: "Amsterdam", score: 69.5, website: "https://www.uva.nl", acceptanceRate: "4.0%", category: "europe_low_tuition" },
  { rank: 64, name: "National Taiwan University (NTU)", country: "Taiwan", city: "Taipei", score: 69.1, website: "https://www.ntu.edu.tw", acceptanceRate: "15.0%", category: "asian_top" },
  { rank: 65, name: "University of Copenhagen", country: "Denmark", city: "Copenhagen", score: 68.7, website: "https://www.ku.dk", acceptanceRate: "15.0%", category: "europe_low_tuition" },
  { rank: 66, name: "Texas A&M University", country: "USA", city: "College Station", score: 68.3, website: "https://www.tamu.edu", acceptanceRate: "63.0%", category: "stem_tech" },
  { rank: 67, name: "University of Texas at Austin", country: "USA", city: "Austin", score: 67.9, website: "https://utexas.edu", acceptanceRate: "29.0%", category: "stem_tech" },
  { rank: 68, name: "Trinity College Dublin", country: "Ireland", city: "Dublin", score: 67.4, website: "https://www.tcd.ie", acceptanceRate: "25.0%", category: "europe_low_tuition" },
  { rank: 69, name: "University of Washington", country: "USA", city: "Seattle", score: 67.0, website: "https://www.washington.edu", acceptanceRate: "48.0%", category: "stem_tech" },
  { rank: 70, name: "KTH Royal Institute of Technology", country: "Sweden", city: "Stockholm", score: 66.5, website: "https://www.kth.se", acceptanceRate: "20.0%", category: "stem_tech" },
  { rank: 71, name: "University of Birmingham", country: "UK", city: "Birmingham", score: 66.1, website: "https://www.birmingham.ac.uk", acceptanceRate: "15.1%", category: "ivy_elite" },
  { rank: 72, name: "University of Southampton", country: "UK", city: "Southampton", score: 65.8, website: "https://www.southampton.ac.uk", acceptanceRate: "20.0%", category: "ivy_elite" },
  { rank: 73, name: "Georgia Institute of Technology", country: "USA", city: "Atlanta", score: 65.4, website: "https://www.gatech.edu", acceptanceRate: "16.0%", category: "stem_tech" },
  { rank: 74, name: "University of Leeds", country: "UK", city: "Leeds", score: 65.0, website: "https://www.leeds.ac.uk", acceptanceRate: "25.0%", category: "ivy_elite" },
  { rank: 75, name: "University of Sheffield", country: "UK", city: "Sheffield", score: 64.7, website: "https://www.sheffield.ac.uk", acceptanceRate: "28.0%", category: "ivy_elite" },
  { rank: 76, name: "Lomonosov Moscow State University", country: "Russia", city: "Moscow", score: 64.3, website: "https://www.msu.ru", acceptanceRate: "12.0%", category: "europe_low_tuition" },
  { rank: 77, name: "University of Zurich", country: "Switzerland", city: "Zurich", score: 64.0, website: "https://www.uzh.ch", acceptanceRate: "20.0%", category: "europe_low_tuition" },
  { rank: 78, name: "University of Hamburg", country: "Germany", city: "Hamburg", score: 63.6, website: "https://www.uni-hamburg.de", acceptanceRate: "18.0%", category: "europe_low_tuition" },
  { rank: 79, name: "Free University of Berlin", country: "Germany", city: "Berlin", score: 63.3, website: "https://www.fu-berlin.de", acceptanceRate: "15.0%", category: "europe_low_tuition" },
  { rank: 80, name: "University of Wisconsin-Madison", country: "USA", city: "Madison", score: 63.0, website: "https://www.wisc.edu", acceptanceRate: "49.0%", category: "stem_tech" },
  { rank: 81, name: "Boston University", country: "USA", city: "Boston", score: 62.7, website: "https://www.bu.edu", acceptanceRate: "14.0%", category: "business_finance" },
  { rank: 82, name: "University of North Carolina at Chapel Hill", country: "USA", city: "Chapel Hill", score: 62.3, website: "https://www.unc.edu", acceptanceRate: "19.0%", category: "ivy_elite" },
  { rank: 83, name: "University of Nottingham", country: "UK", city: "Nottingham", score: 62.0, website: "https://www.nottingham.ac.uk", acceptanceRate: "15.1%", category: "ivy_elite" },
  { rank: 84, name: "Uppsala University", country: "Sweden", city: "Uppsala", score: 61.7, website: "https://www.uu.se", acceptanceRate: "20.0%", category: "europe_low_tuition" },
  { rank: 85, name: "University of Helsinki", country: "Finland", city: "Helsinki", score: 61.4, website: "https://www.helsinki.fi", acceptanceRate: "17.0%", category: "europe_low_tuition" },
  { rank: 86, name: "The University of Auckland", country: "New Zealand", city: "Auckland", score: 61.1, website: "https://www.auckland.ac.nz", acceptanceRate: "45.0%", category: "ivy_elite" },
  { rank: 87, name: "Saitama University", country: "Japan", city: "Saitama", score: 60.8, website: "https://www.saitama-u.ac.jp", acceptanceRate: "22.0%", category: "asian_top" },
  { rank: 88, name: "University of South Florida (ASU/USF Group)", country: "USA", city: "Tampa", score: 60.5, website: "https://www.usf.edu", acceptanceRate: "43.0%", category: "stem_tech" },
  { rank: 89, name: "Arizona State University (ASU)", country: "USA", city: "Tempe", score: 60.1, website: "https://www.asu.edu", acceptanceRate: "88.0%", category: "stem_tech" },
  { rank: 90, name: "University of Oslo", country: "Norway", city: "Oslo", score: 59.8, website: "https://www.uio.no", acceptanceRate: "15.0%", category: "europe_low_tuition" },
  { rank: 91, name: "University of Western Australia", country: "Australia", city: "Perth", score: 59.4, website: "https://www.uwa.edu.au", acceptanceRate: "38.0%", category: "ivy_elite" },
  { rank: 92, name: "University of Geneva", country: "Switzerland", city: "Geneva", score: 59.1, website: "https://www.unige.ch", acceptanceRate: "20.0%", category: "europe_low_tuition" },
  { rank: 93, name: "Ghent University", country: "Belgium", city: "Ghent", score: 58.8, website: "https://www.ugent.be", acceptanceRate: "25.0%", category: "europe_low_tuition" },
  { rank: 94, name: "University of Groningen", country: "Netherlands", city: "Groningen", score: 58.5, website: "https://www.rug.nl", acceptanceRate: "28.0%", category: "europe_low_tuition" },
  { rank: 95, name: "Stockholm University", country: "Sweden", city: "Stockholm", score: 58.1, website: "https://www.su.se", acceptanceRate: "18.0%", category: "europe_low_tuition" },
  { rank: 96, name: "Aalto University", country: "Finland", city: "Espoo", score: 57.8, website: "https://www.aalto.fi", acceptanceRate: "20.0%", category: "stem_tech" },
  { rank: 97, name: "Rice University", country: "USA", city: "Houston", score: 57.5, website: "https://www.rice.edu", acceptanceRate: "8.7%", category: "ivy_elite" },
  { rank: 98, name: "University of Pittsburgh", country: "USA", city: "Pittsburgh", score: 57.2, website: "https://www.pitt.edu", acceptanceRate: "49.0%", category: "stem_tech" },
  { rank: 99, name: "University of Pisa", country: "Italy", city: "Pisa", score: 56.9, website: "https://www.unipi.it", acceptanceRate: "45.0%", category: "europe_low_tuition" },
  { rank: 100, name: "Westminster International University in Tashkent (WIUT)", country: "Uzbekistan", city: "Tashkent", score: 56.5, website: "https://www.wiut.uz", acceptanceRate: "35.0%", category: "local_joint" }
];
